Merge egrep patch, re-export patches, fix patch numbering

diff --git a/rpm/0006-Remove-.gdb_index-support.patch b/rpm/0006-Remove-.gdb_index-support.patch
--- a/rpm/0006-Remove-.gdb_index-support.patch
+++ b/rpm/0006-Remove-.gdb_index-support.patch
@@ -4,14 +4,14 @@ Date: Wed, 18 Sep 2024 11:27:10 +0300
 Subject: [PATCH] Remove .gdb_index support
 
 ---
- scripts/find-debuginfo.in | 16 ----------------
- 1 file changed, 16 deletions(-)
+ scripts/find-debuginfo.in | 20 --------------------
+ 1 file changed, 20 deletions(-)
 
 diff --git a/scripts/find-debuginfo.in b/scripts/find-debuginfo.in
-index 456827e..ffd2e52 100644
+index 2b2e2f2..0685115 100644
 --- a/scripts/find-debuginfo.in
 +++ b/scripts/find-debuginfo.in
-@@ -113,9 +113,6 @@ keep_remove_args=
+@@ -114,9 +114,6 @@ keep_remove_args=
  # with -m arg, add minimal debuginfo to binary.
  include_minidebug=false
  
@@ -21,7 +21,7 @@ index 456827e..ffd2e52 100644
  # Barf on missing build IDs.
  strict=false
  
-@@ -176,9 +173,6 @@ while [ $# -gt 0 ]; do
+@@ -177,9 +174,6 @@ while [ $# -gt 0 ]; do
    -n)
      no_recompute_build_id=true
      ;;
@@ -31,17 +31,21 @@ index 456827e..ffd2e52 100644
    -o)
      if [ -z "${lists[$nout]}" ] && [ -z "${ptns[$nout]}" ]; then
        out=$2
-@@ -469,16 +463,6 @@ do_file()
-     $strict && exit 2
+@@ -470,20 +464,6 @@ do_file()
+     $strict && return 2
    fi
  
 -  # Add .gdb_index if requested.
 -  if $include_gdb_index; then
 -    if type gdb-add-index >/dev/null 2>&1; then
--      gdb-add-index "$f"
+-      gdb-add-index "$f" || {
+-        status=$?
+-        echo >&2 "*** ERROR:: GDB exited with exit status $status during index generation"
+-        return 2
+-      }
 -    else
 -      echo >&2 "*** ERROR: GDB index requested, but no gdb-add-index installed"
--      exit 2
+-      return 2
 -    fi
 -  fi
 -
